# Generated by Django 6.0.2 on 2026-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('ghs', 'GHS'), ('usd', 'USD'), ('cfa', 'CFA')], default='ghs', max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='Optional', max_length=100, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code'),
        ),
    ]
