# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_currency_property_state_property_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(
                choices=[('rent', 'For Rent'), ('sale', 'For Sale')],
                default='rent',
                help_text='Whether the property is for rent or for sale',
                max_length=10,
                verbose_name='Listing type',
            ),
        ),
    ]
